[package]
name = "tauri-bindgen-host-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
tauri-bindgen-gen-host = { path = "../bindgen-gen-host" }
rust-macro-shared = { path = "../rust-macro-shared" }